INSERT INTO portfolio_project
(id, slug, name_zh, name_de, project_type, role_text, summary, technologies, responsibilities, outcomes, facts, keywords, sensitive, enabled)
VALUES
('11111111-1111-1111-1111-111111111111', 'face-attendance', '人脸识别考勤系统', 'Unternehmensweites Gesichtserkennungs- und Zeiterfassungssystem', 'COMPANY', 'Unternehmensprojekt / Einzelentwicklung',
 '本地摄像头与 RTSP 人脸识别客户端配合后台管理员工、照片、打卡及统计，形成完整考勤闭环。',
 'Python, OpenCV, InsightFace, ONNX Runtime, Java 21, Spring Boot 3, Vue 3, MySQL, Redis, Docker Compose, SnailJob, Warm-Flow',
 '端到端架构与开发；Embedding 相似度匹配；远程打卡 API；员工照片同步；日月统计；任务调度与系统集成。',
 '在三个办公地点为约 200 名员工投入使用；客户端部署于现场 Windows 计算机，服务端部署于 Linux。',
 '个人独立开发；约 200 名员工；三个办公地点；只有这里列出的技术和规模可以用于简历。',
 'java,spring boot,python,computer vision,api,integration,docker,workflow,backend,full stack,automation', FALSE, TRUE),
('22222222-2222-2222-2222-222222222222', 'zeitplan', 'ZeitPlan 日程系统', 'ZeitPlan – Tagesplanung und Zeitmanagement', 'PERSONAL', 'Persönliches Projekt / Einzelentwicklung',
 '按德国时间安排每日任务并同步北京时间，提供统计、计时器、奖励机制和 Kindle 状态屏推送。',
 'Java 21, Spring Boot 3.5, React 19, TypeScript, PostgreSQL, Flyway, Docker, Docker Compose, Nginx, Certbot, GitHub Actions, Hetzner',
 '全栈设计开发；5 分钟粒度时间轴；认证；统计；图像与 PDF 生成；Kindle 长轮询同步；自动部署。',
 '部署到 Hetzner，使用 GitHub Actions 构建、测试和 SSH 部署。',
 '个人独立开发；不得声称用户数量或商业成果。',
 'java,spring boot,react,postgresql,flyway,docker,nginx,https,github actions,hetzner,full stack,ci/cd', FALSE, TRUE),
('33333333-3333-3333-3333-333333333333', 'ai-chatbox', '本地 AI 聊天平台', 'Lokal betriebene KI-Chatplattform', 'PERSONAL', 'Persönliches Projekt / Einzelentwicklung',
 '基于本地 Ollama/Qwen3 的聊天应用，支持登录、多轮会话、SSE 流式回复、继续提问建议和限流。',
 'Java 21, Spring Boot 3.4, Spring Security, React 18, PostgreSQL 16, JPA, Flyway, JWT, BCrypt, SSE, Bucket4j, Ollama, Docker Compose, Nginx',
 '认证授权；流式接口；会话持久化；结构化提示词；用户级限流；容器化部署。',
 '所有推理在本地 Ollama 上运行，敏感内容无需发送到外部模型服务。',
 '个人独立开发；模型为 Qwen3 8B；不得添加并发量或用户量。',
 'java,spring boot,react,postgresql,security,jwt,sse,llm,ollama,docker,nginx,ai,backend', FALSE, TRUE),
('44444444-4444-4444-4444-444444444444', 'report-generator', '智能报告自动生成器', 'KI-gestützter Berichtsgenerator', 'CLIENT', 'Kundenprojekt / Einzelentwicklung',
 '读取 Excel、图片、PDF 和 Word 模板，结合 Gemini 结构化生成与校验规则批量生成两类专业 DOCX 报告。',
 'Python, Tkinter, python-docx, openpyxl, Pillow, PyMuPDF, Gemini API, JSON Schema, pywin32, PyInstaller',
 '多模态资料抽取；结构化 AI 输出；金额与身份字段校验；模板渲染；生成清单与日志；Windows 打包。',
 '将多源资料和动态章节合并为可交付 Word 报告。',
 '客户项目、个人独立开发；不得暴露客户身份和输入数据。',
 'python,ai,gemini,structured output,json schema,document automation,validation,word,excel,pdf,api', FALSE, TRUE),
('55555555-5555-5555-5555-555555555555', 'employee-card', '员工卡自动生成打印工具', 'Automatisierte Erstellung und Druck von Mitarbeiterausweisen', 'COMPANY', 'Unternehmensprojekt / Einzelentwicklung',
 'Windows 工具从公司 API 分页获取员工资料，选择员工、下载照片、生成 CR80 卡片并打印。',
 'Python, Tkinter, Pillow, REST API, JSON, CSV, PowerShell, System.Drawing.Printing, Windows',
 'API 集成；分页数据同步；双语 GUI；图片处理与卡片渲染；Windows 打印机集成。',
 '打通公司系统数据到实体员工卡的自动化流程。',
 '个人独立开发；不得公开 API 凭证、公司名称或员工数据。',
 'python,api,integration,automation,desktop,printing,image processing,windows,data pipeline', FALSE, TRUE),
('66666666-6666-6666-6666-666666666666', 'container-batch', '批量创建容器与标签工作流', 'Workflow zur Stapelerstellung von Behältern und Etiketten', 'COMPANY', 'Unternehmensprojekt / Einzelentwicklung',
 '与公司系统集成，批量创建容器记录，生成带 Code128 条码的 A5 标签 PDF并打印。',
 'Python, Tkinter, REST API, JSON, Pillow, PyMuPDF, Code128, pywin32, Windows',
 '桌面工作流；API 记录创建；编码生成；PDF 模板渲染；结果审计文件；打印机集成。',
 '自动化批量记录创建和标签生产流程。',
 '个人独立开发；不得虚构处理数量和节省时间。',
 'python,api,workflow,automation,pdf,barcode,printing,integration,desktop', FALSE, TRUE),
('77777777-7777-7777-7777-777777777777', 'vote-tracker', '实时票数追踪与可视化', 'Echtzeit-Tracking und Visualisierung von Abstimmungsdaten', 'CLIENT', 'Kundenprojekt / Einzelentwicklung',
 '定时抓取公开投票接口，仅在变化时写入 SQLite，并通过本地网页显示可缩放票数曲线。',
 'Python, Flask, SQLite, requests, threading, HTML, CSS, JavaScript, Chart.js, PyInstaller',
 '后台定时采集；变化检测；数据持久化；筛选搜索；交互图表；Windows EXE 打包。',
 '默认每 10 秒采集并避免写入未变化数据。',
 '客户项目、个人独立开发；只描述追踪器，不与自动投票项目混合。',
 'python,flask,sqlite,data collection,visualization,chart.js,threading,desktop,monitoring', FALSE, TRUE),
('88888888-8888-8888-8888-888888888888', 'portfolio', '个人作品集网站', 'Mehrsprachige Portfolio-Webanwendung', 'PERSONAL', 'Persönliches Projekt / Einzelentwicklung',
 '展示个人介绍、项目、在线简历和联系方式的中英双语响应式全栈网站。',
 'React, Java, Spring Boot, Docker, Docker Compose, Nginx, Certbot, GitHub Actions',
 '响应式前端；国际化；后端 API；健康检查；HTTPS；自动构建验证。',
 '支持容器化本地运行和生产部署。',
 '个人独立开发；项目简述中未确认数据库，因此不得添加 PostgreSQL。',
 'react,java,spring boot,frontend,full stack,i18n,docker,nginx,https,ci/cd', FALSE, TRUE),
('99999999-9999-9999-9999-999999999999', 'thesis-cat-3d', '猫咪姿态与 3D 生成论文工作流', 'Modulare Pipeline für Katzenpose und 3D-Modellgenerierung', 'THESIS', 'Masterarbeit / Einzelentwicklung',
 'ComfyUI 工作流将猫视频的 DeepLabCut 关键点、Gemini 图像理解与重绘、Hunyuan3D 单图建模串联起来。',
 'Python, ComfyUI, DeepLabCut, TensorFlow, CUDA, OpenCV, PyTorch, Gemini API, Hunyuan3D 2.0, Diffusers, Transformers, Trimesh, PyMeshLab, GLB',
 '自定义 ComfyUI 节点；姿态推理；坐标语义化；图像生成；去背景；三维网格生成清理和导出。',
 '输出关键点数据、标注视频、黏土风参考图和约 5 万面的 GLB 网格。',
 '硕士论文；12 个猫身体关键点；不得声称产品化用户或商业部署。',
 'python,ai,computer vision,deep learning,pose estimation,generative ai,3d,comfyui,gpu,pipeline,research', FALSE, TRUE),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'artguide', 'ArtGuide 艺术知识图谱与 AI 助手', 'ArtGuide – Wissensgraph und lokaler KI-Assistent', 'ACADEMIC', 'Hochschulprojekt',
 '把艺术 RDF 知识图谱 SPARQL 查询和本地 Ollama 聊天整合在一个全栈页面中。',
 'Angular, Django, Python, Apache Jena Fuseki, RDF, SPARQL, Ollama, Phi-3, LangChain, SSE, Docker',
 '知识图谱查询；后端转发；本地大模型接入；会话上下文；SSE 流式响应；容器编排。',
 '使用约 96 MB 的 art.ttl 数据集。',
 '高校项目；不得声称单独开发或生产用户。',
 'python,django,angular,knowledge graph,rdf,sparql,llm,ollama,langchain,sse,docker', FALSE, TRUE),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'ready2code', 'Ready2Code 编程学习平台', 'Ready2Code – interaktive Lernplattform', 'ACADEMIC', 'Hochschulprojekt / Teamprojekt',
 '为编程初学者提供课程、关卡、多种交互练习、进度积分、管理员编辑和内容导入导出。',
 'Vue, FastAPI, Python, MongoDB, Redis, SMTP, OpenTelemetry, Docker, Traefik, Terraform, Ansible, OpenStack',
 '学习内容与练习；认证；进度和排行榜；管理功能；可观测性；基础设施自动化。',
 '平台由 Hochschule Darmstadt 开发，项目内容主要为德语。',
 '团队高校项目；只能描述本人能够证明的贡献，当前种子数据未记录个人贡献细节。',
 'vue,python,fastapi,mongodb,redis,opentelemetry,docker,terraform,ansible,cloud,education,team', FALSE, TRUE),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 'pdf-compressor', 'PDF 批量压缩工具', 'Desktop-Anwendung zur Stapelkomprimierung von PDF-Dateien', 'PERSONAL', 'Persönliches Projekt / Einzelentwicklung',
 '支持拖拽、文件夹递归、四档压缩、后台线程和进度显示的 Windows PDF 批量压缩工具。',
 'Python, Tkinter, tkinterdnd2, PyMuPDF, Pillow, threading, queue, Windows, PyInstaller',
 '桌面 GUI；批量导入；后台处理；页面重渲染压缩；进度通信；输出重名处理。',
 '提供四种压缩档位并保持 GUI 响应。',
 '个人独立开发；不得添加未测量的压缩率。',
 'python,desktop,pdf,image processing,multithreading,queue,windows,automation,ux', FALSE, TRUE);
